#!/data/data/com.termux/files/usr/bin/bash
clear
kill_color=$'\e[0m'
url=$1

echo -e "\e[036m" "╔════════════════════════════════════════╗"                                                                          
echo -e "\e[032m" "║ ♚ Tool Name : kimo48/youtube          ║"
echo -e "\e[032m" "║ ♚ Author : kimo                       ║"
echo -e "\e[032m" "║ ♚ Github : github.com/kimo48/youtube  ║"
echo -e "\e[036m" "╠════════════════════════════════════════╝"
echo -e "\e[032m" "╠═▶ 1.youtube"
echo -e "\e[032m" "╠═▶ 2.tiktok"
 printf "\e[032m  ╚═:➤ $kill_color"
read n

if [ "$n" == '1' ]; then
[ ! -d "/data/data/com.termux/files/home/storage/shared/Youtube" ] && mkdir "/data/data/com.termux/files/home/storage/shared/Youtube"
youtube-dl -x --audio-format mp3 -f bestaudio --audio-quality 0 -c -i "$url" -o "/data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s"
else

if [ "$n" == '2' ]; then
echo "$url"

[ ! -d "/data/data/com.termux/files/home/storage/shared/Tiktok" ] && mkdir "/data/data/com.termux/files/home/storage/shared/Tiktok"

python /data/data/com.termux/files/home/download/download_tiktok.py "$url"

path="$(echo $url | grep / | cut -d/ -f4-)"
echo $path | sed 's#/.*##g'

read n

play "/data/data/com.termux/files/home/storage/shared/Tiktok/$n"
echo "download complete"

fi
fi
