#!/bin/bash
clear
url=$1
echo "kimo"
echo "7: Download with youtube-dl and extract audio"
echo "8: Download with Tiktok"
read n

if [ "$n" == '7' ]; then
[ ! -d "/data/data/com.termux/files/home/storage/shared/Youtube" ] && mkdir "/data/data/com.termux/files/home/storage/shared/Youtube"
youtube-dl -x --audio-format mp3 -f bestaudio --audio-quality 0 -c -i "$url" -o "/data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s"
else

if [ "$n" == '8' ]; then
echo "$url"

[ ! -d "/data/data/com.termux/files/home/storage/shared/Tiktok" ] && mkdir "/data/data/com.termux/files/home/storage/shared/Tiktok/"

python /data/data/com.termux/files/home/download/download_tiktok.py "$url" "/data/data/com.termux/files/home/storage/shared/Tiktok/1.mp3"

echo "download complete"

fi
fi
