#!/data/data/com.termux/files/usr/bin/bash
clear
kill_color=$'\e[0m'
url=$1
you="yout"
tik="tik"

echo -e "\e[036m" "╔════════════════════════════════════════╗"                                                                          
echo -e "\e[032m" "║ ♚ Tool Name : kimo48/youtube          ║"
echo -e "\e[032m" "║ ♚ Author : kimo                       ║"
echo -e "\e[032m" "║ ♚ Github : github.com/kimo48/youtube  ║"
echo -e "\e[036m" "╠════════════════════════════════════════╝"
echo -e "\e[032m" "╠═▶ 1.youtube mp3"
echo -e "\e[032m" "╠═▶ 2.tiktok video"
echo -e "\e[032m" "╠═▶ 3.tiktok mp3"
echo -e "\e[032m" "╠═▶ 4.facebook video"
 printf "\e[032m  ╚═:➤ $kill_color"
 
if [[ "$url" =~ .*"$you".* ]]; then
  echo "youtube"
  n=1
else
if [[ "$url" =~ .*"$tik".* ]]; then
  echo "tiktok"
  n=9
fi  
fi 

#read z

if [ "$n" == '1' ]; then
[ ! -d "/data/data/com.termux/files/home/storage/shared/Youtube" ] && mkdir "/data/data/com.termux/files/home/storage/shared/Youtube"
youtube-dl -x --audio-format mp3 -f bestaudio --audio-quality 0 -c -i "$url" -o "/data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s"

#play "/data/data/com.termux/files/home/storage/shared/Youtube/$title.mp3"

else

if [ "$n" == '9' ]; then

read n

if [ "$n" == '2' ]; then
echo "download video"
echo "$url"

[ ! -d "/data/data/com.termux/files/home/storage/shared/Tiktok" ] && mkdir "/data/data/com.termux/files/home/storage/shared/Tiktok"
python /data/data/com.termux/files/home/download/download_tiktok_mp4.py "$url"
echo "download complete"
else

if [ "$n" == '3' ]; then
echo "download mp3"
echo "$url"

[ ! -d "/data/data/com.termux/files/home/storage/shared/Tiktok" ] && mkdir "/data/data/com.termux/files/home/storage/shared/Tiktok"

python /data/data/com.termux/files/home/download/download_tiktok_mp3.py "$url"

#mp2="$(echo $url | grep / | cut -f1-4 -d)"

mp1="$(echo $url | grep / | cut -d"/" -f4)"
echo $mp1

#mp2= "$(echo $mp1 | sed 's#/.*##g')"
#echo $mp2

mp3="$(echo "${mp1}.mp3")"
echo $mp3

#read n

play "/data/data/com.termux/files/home/storage/shared/Tiktok/$mp3"
echo "download complete"


if [ "$n" == '4' ]; then
echo "download video"
echo "$url"

[ ! -d "/data/data/com.termux/files/home/storage/shared/Facebook" ] && mkdir "/data/data/com.termux/files/home/storage/shared/Facebook"
python /data/data/com.termux/files/home/download/download_facebook_mp4.py "$url"
echo "download complete"


fi
fi
fi
fi
fi
